### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by eclipseo** [fooyin/fooyin#99]
Hello,

So would you be interested in a Flatpak package?

I have sent you a couple PR in order to do this.

Here is my current YAML:

```YAML
app-id: org.fooyin.fooyin
runtime: org.kde.Platform
runtime-version: '6.7'
sdk: org.kde.Sdk
command: fooyin
add-extensions:
  org.freedesktop.Platform.ffmpeg-full:
    directory: lib/ffmpeg
    version: '23.08'
    add-ld-path: .
finish-args:
  - '--device=dri'
  - '--filesystem=xdg-download'
  - '--filesystem=xdg-music'
  - '--filesystem=xdg-run/pipewire-0'
  - '--filesystem=/run/media'
  - '--own-name=org.mpris.MediaPlayer2.fooyin'
  - '--persist=.config'
  - '--share=ipc'
  - '--share=network'
  - '--socket=fallback-x11'
  - '--socket=pulseaudio'
  - '--socket=wayland'
  - '--system-talk-name=org.freedesktop.UDisks2'
  - '--talk-name=org.freedesktop.Notifications'
  - '--talk-name=org.gtk.Notifications'
  - '--talk-name=org.kde.StatusNotifierWatcher'
  - '--talk-name=org.mpris.MediaPlayer2.*'
cleanup:
  - '*.a'
  - '*.la'
  - '/include'
  - '/lib/cmake'
  - '/lib/pkgconfig'
  - '/mkspecs'
  - '/share/aclocal'
  - '/share/doc/KDSingleApplication-qt6'
cleanup-commands:
  - 'mkdir -p ${FLATPAK_DEST}/lib/ffmpeg'
modules:
  - name: KDSingleApplication
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - '-DCMAKE_BUILD_TYPE=Release'
      - '-DKDSingleApplication_QT6=ON'
      - '-DKDSingleApplication_EXAMPLES=OFF'
    sources:
      - type: git
        url: https://github.com/KDAB/KDSingleApplication
        tag: 'v1.1.0'
        commit: cb0c664b40d3b31bad30aa3521eff603162ed0bd
        x-checker-data:
          type: anitya
          project-id: 370439
          stable-only: true
  - name: taglib
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - '-DCMAKE_BUILD_TYPE=Release'
      - '-DBUILD_SHARED_LIBS=ON'
    sources:
      - type: git
        url: https://github.com/taglib/taglib
        tag: 'v2.0.1'
        commit: ebf4c5bbb1ce85a71764122cbc3cc3f556e66586
        x-checker-data:
          type: anitya
          project-id: 1982
          stable-only: true
  - name: fooyin
    buildsystem: cmake-ninja
    builddir: true
    post-install:
      - rm -rfv ${FLATPAK_DEST}/share/metainfo/org.fooyin.fooyin.metainfo.xml
      - rm -rfv ${FLATPAK_DEST}/share/applications/org.fooyin.fooyin.desktop
      - install -Dpm644 ../org.fooyin.fooyin.metainfo.xml ${FLATPAK_DEST}/share/metainfo/org.fooyin.fooyin.metainfo.xml
      - install -Dpm644 ../org.fooyin.fooyin.desktop ${FLATPAK_DEST}/share/applications/org.fooyin.fooyin.desktop
      - |
        for size in 16 22 32 48 64 128 256 512; do
          if [ -f ${FLATPAK_DEST}/share/icons/hicolor/${size}x${size}/apps/fooyin.png ]; then
            mv ${FLATPAK_DEST}/share/icons/hicolor/${size}x${size}/apps/fooyin.png ${FLATPAK_DEST}/share/icons/hicolor/${size}x${size}/apps/org.fooyin.fooyin.png
          fi
        done
        if [ -f ${FLATPAK_DEST}/share/icons/hicolor/scalable/apps/fooyin.svg ]; then
          mv ${FLATPAK_DEST}/share/icons/hicolor/scalable/apps/fooyin.svg ${FLATPAK_DEST}/share/icons/hicolor/scalable/apps/org.fooyin.fooyin.svg
        fi
    config-opts:
      - '-DBUILD_ALSA=OFF'
      - '-DCMAKE_BUILD_TYPE=Release'
    sources:
      - type: git
        url: https://github.com/ludouzi/fooyin
        tag: 'v0.4.2'
        commit: a7516f2a3ed3cbfe7fdb4f15a2567bb3ffeb8ae1
        x-checker-data:
          type: anitya
          project-id: 372406
          stable-only: true
      - type: file
        path: 'org.fooyin.fooyin.desktop'
      - type: file
        path: 'org.fooyin.fooyin.metainfo.xml'
      - type: patch
        path: '0001-Add-option-to-disable-ALSA-with-PipeWire-as-a-defaul.patch'
```

Here is my ready to go repo: https://github.com/eclipseo/flathub/tree/org.fooyin.fooyin

Here is the template for a PR:

```
<!-- ⚠️  The submission PR must be against the `new-pr` branch ⚠️  -->

### Please confirm your submission meets all the criteria

<!-- Please replace each `[ ]` by `[X]` when the step is complete -->

- [x] Please describe your application briefly.
- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
```

We're here:

- [x] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**

The other issue is:

- [x] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.

The doc regarding the application id: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
https://docs.flathub.org/docs/for-app-authors/verification#website

If you use org.fooyin.fooyin, it assumes your control the fooyin.org domain.

I can go through the YAML if needed to explain each part.

**Comment by ludouzi** [comment]
Firstly, thanks for all the work you've done so far. It's really appreciated.

I'm definitely interested in a Flatpak package. I'll go over those PRs a bit later.

The YAML looks good from a quick glance. One aspect I'm not sure on is the single persist directory (`.config`). Fooyin also needs to load data from `.local/share/fooyin` and `.cache/fooyin`. Are these automatically handled by the Flatpak?

I've just taken ownership of fooyin.org, so that shouldn't be a problem.

**Comment by eclipseo** [comment]
> Firstly, thanks for all the work you've done so far. It's really appreciated.
> 
> I'm definitely interested in a Flatpak package. I'll go over those PRs a bit later.
> 
> The YAML looks good from a quick glance. One aspect I'm not sure on is the single persist directory (`.config`). Fooyin also needs to load data from `.local/share/fooyin` and `.cache/fooyin`. Are these automatically handled by the Flatpak?
> 

Actually I'm not sure if I should persist .config. Flatpak data are not stored in the root of the home folder but,  sandboxed under:

ll ~/.var/app/org.fooyin.fooyin/
drwxr-xr-x@ - bob 18 mai   04:56 cache
drwxr-xr-x@ - bob 18 mai   05:04 config
drwxr-xr-x@ - bob 18 mai   04:57 data


Persist does this:

> If an application hardcodes a path in $HOME and you don’t grant home access you can use --persist and it will map the $HOME directory to your private directory e.g. --persist=.mozilla. If the application takes args to set config/data dirs then use them.

So I don't think it is actually needed, because it works without.

> I've just taken ownership of fooyin.org, so that shouldn't be a problem.
Great.

**Comment by eclipseo** [comment]
Latest YAML version:

```
app-id: org.fooyin.fooyin
runtime: org.kde.Platform
runtime-version: '6.7'
sdk: org.kde.Sdk
command: fooyin
add-extensions:
  org.freedesktop.Platform.ffmpeg-full:
    directory: lib/ffmpeg
    version: '23.08'
    add-ld-path: .
finish-args:
  - '--device=dri'
  - '--filesystem=xdg-download'
  - '--filesystem=xdg-music'
  - '--filesystem=xdg-run/pipewire-0'
  - '--filesystem=/run/media'
  - '--own-name=org.mpris.MediaPlayer2.fooyin'
  - '--share=ipc'
  - '--share=network'
  - '--socket=fallback-x11'
  - '--socket=pulseaudio'
  - '--socket=wayland'
  - '--system-talk-name=org.freedesktop.UDisks2'
cleanup:
  - '*.a'
  - '*.la'
  - '/include'
  - '/lib/cmake'
  - '/lib/alsa-lib/pkgconfig'
  - '/lib/pkgconfig'
  - '/mkspecs'
  - '/share/aclocal'
  - '/share/doc/KDSingleApplication-qt6'
cleanup-commands:
  - 'mkdir -p ${FLATPAK_DEST}/lib/ffmpeg'
modules:
  - name: alsa-lib
    buildsystem: simple
    builddir: true
    build-commands:
      - ./configure --prefix=${FLATPAK_DEST} --libdir=${FLATPAK_DEST}/lib/alsa-lib
      - make -j$FLATPAK_BUILDER_N_JOBS
      - make install
    sources:
      - type: archive
        url: https://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.11.tar.bz2
        sha256: 9f3f2f69b995f9ad37359072fbc69a3a88bfba081fc83e9be30e14662795bb4d
        x-checker-data:
          type: anitya
          project-id: 38
          stable-only: true
          url-template: https://www.alsa-project.org/files/pub/lib/alsa-lib-$version.tar.bz2
  - name: KDSingleApplication
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - '-DCMAKE_BUILD_TYPE=Release'
      - '-DKDSingleApplication_QT6=ON'
      - '-DKDSingleApplication_EXAMPLES=OFF'
    sources:
      - type: git
        url: https://github.com/KDAB/KDSingleApplication
        tag: 'v1.1.0'
        commit: cb0c664b40d3b31bad30aa3521eff603162ed0bd
        x-checker-data:
          type: anitya
          project-id: 370439
          stable-only: true
  - name: fooyin
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - '-DCMAKE_BUILD_TYPE=Release'
    sources:
      - type: git
        url: https://github.com/ludouzi/fooyin
        tag: 'v0.4.2'
        commit: a7516f2a3ed3cbfe7fdb4f15a2567bb3ffeb8ae1
        x-checker-data:
          type: anitya
          project-id: 372406
          stable-only: true
      - type: patch
        path: '0001-Add-option-to-disable-ALSA-with-PipeWire-as-a-defaul.patch'
      - type: patch
        path: '0001-Use-the-standard-reverse-DNS-schema-everywhere.patch'

```
